### PR TITLE
Dynamically fetching champion-IDs from CommunityDragon on startup

### PR DESCRIPTION
**Pull request by vinzynth**
I got tired from my projects crashing because they can't find a certain championID in the constants, mainly because it's a new champion which got recently added.

So i added a request to a champion list from the PBE patch provided by the CommunityDragon project([dataset link](https://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/v1/champion-summary.json)).

Now instead of updating the a new version of the library, i can just simply restart my services, and there is no need anymore to manually add a new champion id.

Since I think this is a good thing to have, I've created a pull request with the described functionality. I don't know tho, if you want this feature as part of your library, so i neither haven't pumped the version code, nor created a testcase for this feature.

Let me know what you think.

### CODE REVIEW

**Comment by Sansossio** [comment]
Update package.json version

**Comment by vinzynth** [comment]
I've updated to version to 1.35, and added a setInterval call, so the champion ids get updated once every day.
The linter still fails, and i'm not sure if it makes sense to make the interval call optional with a environment variable.

**Comment by Sansossio** [comment]
I'd add an environment variable to enable that setinterval due that is an optional feature and the library shouldn't do anything without user action. The linter problems must be fixed

**Comment by vinzynth** [comment]
Alrighty, I'll take care of this a bit later today!

**Comment by vinzynth** [comment]
Should be done now! Happy holidays!

**Comment by Sansossio** [comment]
Approved! Merry christmas!

**Pull request merged**
