### PR TITLE
Add Rell champion ID to champions.ts

### PR DESCRIPTION
**Pull request by Gabb-c**

### CODE REVIEW

**Comment by Sansossio** [comment]
Please, update package.json version

**Comment by Gabb-c** [comment]
> Please, update package.json version

It's updated. Now on 1.34

**Comment by Sansossio** [comment]
@Gabb-c are you sure? I cannot see that change

**Comment by Sansossio** [comment]
You updated packagelock, you have to change package.json

**Comment by Gabb-c** [comment]
> You updated packagelock, you have to change package.json

Oh jezz... Sorry for this

**Pull request closed without merging**
