### PR TITLE
Add LOL-STATUS-V4

### PR DESCRIPTION
**Pull request by t-miller**

### CODE REVIEW

**Comment by ciriousjoker** [comment]
@t-miller What's the status of this? So far, this just adds another line to the readme

**Comment by t-miller** [comment]
Yeah the idea is just to update the README to match the last addition of functionality

**Review by ciriousjoker — DISMISSED** [review]
lgtm

**Comment by ciriousjoker** [comment]
@Sansossio Not quite sure why the code coverage improved, but hey

**Review by Sansossio — APPROVED** [review]

**Pull request merged**
