### PR TITLE
Added start and end time to MatchQueryV5DTO

### LINKED ISSUE #63: Query Parameters for Start and EndTime in MatchQueryV5DTO missing
Hello,

if you look into the official Riot API Documentation for the MatchV5 endpoints you can see, that there are two query parameters for the startTime and the endTime which get used to filter out matches that are not in the timeframe.

These two query parameters are missing in the MatchQueryV5DTO.

Greetings
Anno

### PR DESCRIPTION
**Pull request by annnoo**
fixes #63 
Added startTime and endTime to the MatchQueryV5DTO as documented in: https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID

### CODE REVIEW

**Comment by annnoo** [comment]
@Sansossio Is there something missing in my PR?

**Comment by CiriousJoker** [comment]
Don't these values also need to be passed to riot via the http request?

I don't know the codebase off the top of my head but I doubt these two lines are enough

**Comment by annnoo** [comment]
@CiriousJoker  Adding these two values is everything you have to do, because the other two work (currently even using this fix by myself by extending the MatchQueryV5DTO)

The MatchV5 Request, which takes the MatchQueryV5DTO as a parameter, calls the request function of the BaseAPI class.
https://github.com/Sansossio/twisted/blob/71395ec4539ea5546003d2d92135686537e2ebf7/src/apis/lol/match/match-v5.ts#L44 

This request function takes the provided object (in the case of the MatchV5 Request it is the MatchQueryV5DTO) and adds all properties as query parameters.

https://github.com/Sansossio/twisted/blob/71395ec4539ea5546003d2d92135686537e2ebf7/src/base/base.ts#L214

**Comment by CiriousJoker** [comment]
I ultimately don't maintain this repo, but this PR looks good to me. Just maybe add a test case for the new parameters.

**Comment by Sansossio** [comment]
@annnoo the pr looks good for me.
Please update package.json version

**Review by Sansossio — APPROVED** [review]

**Pull request merged**
